config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  resources :blog_posts

  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    has_rich_text :content 

    validates :title, presence: true
    validates :content, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController 
    
    before_action :set_blog_post, only: [:show, :edit, :update, :destroy] #except:[:index, :new, :create] can also do it this way

    def index
        @blog_posts = BlogPost.all
    end
    def show   
    end
    def new 
        @blog_post = BlogPost.new
    end
    def create
        @blog_post = BlogPost.new(blog_post_params)
        if @blog_post.save
            redirect_to @blog_post
        else
            render :new, status: :unprocessable_entity #use new template instead if error
    end
end
    def edit 
    end
    def update
        if @blog_post.update(blog_post_params)
            redirect_to @blog_post
        else
            render :edit, status: :unprocessable_entity
        end
    end
    def destroy
        @blog_post.destroy
        redirect_to root_path
    end

private

    def blog_post_params
        params.require(:blog_post).permit(:title,:content)
    end
    def set_blog_post
        @blog_post = BlogPost.find(params[:id])
    rescue ActiveRecord::RecordNotFound
        redirect_to root_path #redirect to root
    end
    
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post do |form| %>
    <% if form.object.errors.any? %>
    <div>
    <% form.object.errors.full_messages.each do |messages| %>
        <div> <%= messages %> </div>
    <% end %>
    </div>
<% end %>
<div>
    <%= form.label :title%>
    <%= form.text_field :title %>
</div>

<div>
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
</div>

<%= form.button class:"bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 border border-blue-700 rounded" %>

<%end%>

app/views/blog_posts/_homebtn.html.erb
<%= button_to "Home ", root_path,method: :get, class:"bg-indigo-500 hover:bg-indigo-600 text-white font-bold py-2 px-4 border border-blue-700 rounded"%>

app/views/blog_posts/edit.html.erb
<h1> Edit Blog post </h1>
<%= render partial: "homebtn" %>
<br/>
<%= render partial: "form", locals: {blog_post: @blog_post} %>

<%= button_to "Delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure you want to delete this post? "}, 
class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 border border-blue-700 rounded" %>

app/views/blog_posts/index.html.erb
<h1 style="text-purple-500"> Travel Blog</h1>

<h3> </h3><button onclick="location.href = 'http://localhost/test/';" class="float-left submit-button" 
style="border:none; background-color:#C486EB; color:white; padding: 15px 32px; cursor: pointer; text-align: center; display: inline-block;  font-size: 14px;">
Go to AirBnb Searcher</button>  <br/>

<h2> Blog posts <h2>

<% @blog_posts.each do |blog_post| %>
    <h3> <%= link_to blog_post.title, blog_post_path(blog_post.id) %> </h3> 
    
    <%= blog_post.content%>
<% end %>

<div>
    
    <%= button_to "New Post", new_blog_post_path, method: :get, 
    class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded padding-bottom 500px float-right" %>  

</div>

app/views/blog_posts/new.html.erb
<h1> New blog posts </h1>

<%= render partial: "homebtn" %> <br/>

<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<h1><%= @blog_post.title %> </h1>

<%= render partial: "homebtn" %> <br/>

<%= @blog_post.content %> 
<br/>
<%= button_to "Edit", edit_blog_post_path(@blog_post),method: :get, 
class: "bg-red-300 hover:bg-red-500 text-white font-bold py-2 px-4 border border-blue-700 rounded" %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto">
      <%= yield %>
  </body>
  
</html>